[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "serverless-http"]
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true