[functions]
  external_node_modules = ["express", "serverless-http", "ejs"]
  node_bundler = "esbuild"
  include_files = ["views/**", "public/**"]
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
